[tool.poetry]
name = "papermerge-core"
version = "2.1.dev1"
description = "Core package for Papermerge DMS, which is an open source document management system designed for scanned documents"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
license = "Apache 2.0 License"

[tool.poetry.dependencies]
python = "~3.8"
django = "^3.2"
djangorestframework = "^3.12"
django-cors-headers = "^3.9.0"
djangorestframework-jsonapi = "^4.2"
django_filter = "^21.1"
channels = "^3.0"
channels-redis = "^3.2"
redis = "^3.5"
ocrmypdf = "^12.7.2"
ocrmypdf-papermerge = "^0.3"
django-dynamic-preferences = "^1.10"
celery = "^5.0"
django-taggit = "^2.1"
pyyaml = "^5.4"
lxml = "^4.6"
django-celery-results = "^2.2"
django-polymorphic = "^3.0"
django-mptt = "^0.11"
django-polymorphic-tree = "^2.0"
django-modelcluster = "^5.1"
persisting-theory = "^0.2"
python-magic = "^0.4"
uritemplate = "^4.1.1"
configula = "^0.4.0"
uWSGI = "^2.0.20"
psycopg2 = "^2.9.2"
psycopg2-binary = "^2.9.2"
daphne = "^3.0.2"
django-elasticsearch-dsl = "^7.2.1"
django-rest-knox = "^4.2.0"
drf-spectacular = "^0.22.0"
drf-spectacular-sidecar = "^2022.3.21"


[tool.poetry.dev-dependencies]
pytest = "^6.2"
pytest-django = "^4.4"
pycodestyle = "^2.8"
django-extensions = "^3.1"
ipython = "^8.0.1"
pre-commit = "^2.17.0"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="tests.config.settings"
django_find_project = false

[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

