[tool.poetry]
name = "papermerge-core"
version = "2.1.dev1"
description = "Open source document management system designed for scanned documents"
authors = ["Eugen Ciur <eugen@papermerge.com>"]
license = "Apache 2.0 License"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.2"
djangorestframework = "^3.12"
django-cors-headers = "^3.9.0"
djangorestframework-jsonapi = "^4.2"
django_filter = "^21.1"
channels = "^3.0"
channels-redis = "^3.2"
redis = "^3.5"
ocrmypdf = "^12.7.2"
ocrmypdf-papermerge = "^0.3"
mglib = "^1.3.8"
django-dynamic-preferences = "^1.10"
celery = "^5.0"
django-taggit = "^1.3"
pyyaml = "^5.4"
lxml = "^4.6"
django-celery-results = "^2.2"
django-polymorphic = "^3.0"
django-mptt = "^0.11"
django-polymorphic-tree = "^2.0"
django-modelcluster = "^5.1"
persisting-theory = "^0.2"
python-magic = "^0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
