version: '3.7'
services:
  app:
    image: ${IMAGE}:${TAG}
    ports:
      - "8000:8090"
    depends_on:
      - app_init
    volumes:
      - media_root:/opt/media
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASS=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
  app_init:
    image: ${IMAGE}:${TAG}
    depends_on:
      - db
      - redis
    command: init
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASS=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
  redis:
    image: 'redis:6'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'
volumes:
  postgres_data:
  media_root:
  redisdata:
