version: '3.7'
services:
  app:
    image: ${APP_IMAGE}:${APP_TAG}
    ports:
      - "7000:8090"
    depends_on:
      - app_init
    volumes:
      - media_root:/opt/media
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASSWORD=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    labels:
      - traefik.backend=backend
    networks:
      - traefik
  app_init:
    image: ${APP_IMAGE}:${APP_TAG}
    depends_on:
      - db
      - redis
    command: init
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASSWORD=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    networks:
      - traefik
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  networks:
    - traefik
  redis:
    image: 'redis:6'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'
    networks:
      - traefik
  traefik:
    image: "traefik:v2.5"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8000"
    networks:
      - traefik
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  papermergejs:
    image: ${PAPERMERGE_JS_IMAGE}:${PAPERMERGE_JS_TAG}
    ports:
      - "9000:80"
    networks:
      - traefik
    labels:
      - traefik.backend=frontend

volumes:
  postgres_data:
  media_root:
  redisdata:

networks:
  traefik:
    name: traefik