version: '3.7'
services:
  worker: # celery worker
    image: ${APP_IMAGE}:${APP_TAG}
    volumes:
      - media_root:/app/media
    command: worker
    depends_on:
      - backend_init
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASSWORD=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - PAPERMERGE_REDIS_HOST=${REDIS_HOST}
      - PAPERMERGE_REDIS_PORT=${REDIS_PORT}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - DJANGO_SETTINGS_MODULE=config.settings
  backend:  # rest api backend
    image: ${APP_IMAGE}:${APP_TAG}
    depends_on:
      - backend_init
    volumes:
      - media_root:/app/media
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASSWORD=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - PAPERMERGE_REDIS_HOST=${REDIS_HOST}
      - PAPERMERGE_REDIS_PORT=${REDIS_PORT}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - DJANGO_SETTINGS_MODULE=config.settings
  backend_init:
    image: ${APP_IMAGE}:${APP_TAG}
    depends_on:
      - db
      - redis
    command: init
    environment:
      - PAPERMERGE_SECRET_KEY=${SECRET_KEY}
      - PAPERMERGE_DATABASE_TYPE=postgres
      - PAPERMERGE_DATABASE_USER=${DB_USER}
      - PAPERMERGE_DATABASE_NAME=${DB_NAME}
      - PAPERMERGE_DATABASE_PASSWORD=${DB_PASSWORD}
      - PAPERMERGE_DATABASE_HOST=${DB_HOST}
      - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  postgres_data:
  media_root:
  redisdata:
