name: Create OpenApi Schema PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      PAPERMERGE__MAIN__SECRET_KEY: abc
      PAPERMERGE__SEARCH__ENGINE: whoosh
      DJANGO_SETTINGS_MODULE: config.settings
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout openapi schema
        uses: actions/checkout@v3
        with:
          repository: papermerge/openapi-schema
          path: openapi-schema

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd main
          poetry install
          cd docker/dev
          poetry run task spectacular > ../../../openapi-schema/openapi-schema.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            openapi-schema/*.yaml
        path: openapi-schema
