name: Version Bump

on:
  workflow_dispatch:
    inputs:
      publish-pypi:
        description: 'Publish to PYPI ?'
        required: true
        default: true
      publish-docker-image:
        description: 'Publish to docker image to ghcr.io/dockerhub ?'
        required: true
        default: true


jobs:
  version-bump:
    runs-on: ubuntu-latest
    outputs:
      old-version: ${{ steps.step-version-bump.outputs.OLD_VERSION }}
      new-version: ${{ steps.step-version-bump.outputs.NEW_VERSION }}
    steps:
      - uses: actions/checkout@master

      - name: Version bump
        id: step-version-bump
        uses: papermerge/banger@master
        with:
          files_list: "pyproject.toml,papermerge/core/version.py"

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "version bump ${{steps.step-version-bump.outputs.OLD_VERSION}} -> ${{steps.step-version-bump.outputs.NEW_VERSION}}" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


  publish-pypi:
    runs-on: ubuntu-latest
    needs: version-bump
    if: ${{ github.event.inputs.publish-pypi == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish package
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build


  build-and-push-to-docker-hub:
    name: Dockerhub build/push
    needs: version-bump
    if: ${{ github.event.inputs.publish-docker-image == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: papermerge/papermerge:${{needs.version-bump.outputs.new-version}}
          file: docker/prod/Dockerfile


  build-and-push-image-to-ghcr:
    name: ghcr.io build/push
    if: ${{ github.event.inputs.publish-docker-image == 'true' }}
    needs: version-bump
    runs-on: ubuntu-latest
    env:
      papermerge_image: ghcr.io/papermerge/papermerge
      swagger_ui_image: ghcr.io/papermerge/swagger-ui
      redoc_image: ghcr.io/papermerge/redoc
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.papermerge_image }}:${{needs.version-bump.outputs.new-version}}, ${{ env.papermerge_image }}:latest
          file: docker/prod/Dockerfile

      - name: Build and push swagger-ui
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.swagger_ui_image }}:${{needs.version-bump.outputs.new-version}}, ${{ env.swagger_ui_image }}:latest
          file: docker/Dockerfile.swagger

      - name: Build and push redoc
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: ${{ env.redoc_image }}:${{needs.version-bump.outputs.new-version}}, ${{ env.redoc_image }}:latest
          file: docker/Dockerfile.redoc
